### ISSUE TITLE
invalid URL, scheme is not http

### ISSUE THREAD

**Issue by Ravour** [icyleaf/bandwagon-exporter#32]
xporter-bandwagon-exporter-1  | thread 'tokio-runtime-worker' panicked at 'Failes to fetch api rate limit status.: hyper::Error(Connect, "invalid URL, scheme is not http")', src/server.rs:28:4
exporter-bandwagon-exporter-1  | thread 'tokio-runtime-worker' panicked at 'Failes to fetch node info.: hyper::Error(Connect, "invalid URL, scheme is not http")', src/server.rs:16:6
在本地和服务器上跑docker-compose都报上述错误

**Comment by icyleaf** [comment]
改用 http 地址试试
