### ISSUE TITLE
Broken 

### ISSUE THREAD

**Issue by penggongkui-job** [icyleaf/bandwagon-exporter#94]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `node_ip`", line: 270, column: 1)', src/bandwagon.rs:91:63

**Comment by JasonLiuLiuLiuLiu** [comment]
also have this issue.

```
thread 'tokio-runtime-worker' panicked at src/bandwagon.rs:89:64:
called `Result::unwrap()` on an `Err` value: Error("missing field `node_ip`", line: 271, column: 1)

```

**Comment by icyleaf** [comment]
i have not use bandwagon now, please review api response, is the key `node_ip` exists?

https://api.64clouds.com/v1/getServiceInfo?veid={veid}&api_key={api-key}

**Comment by icyleaf** [comment]
fixed
